### ISSUE TITLE
能不能让用户自己定义json格式或者让用户直接传json就好了，

### ISSUE THREAD

**Issue by 5454267364** [xuexiangjys/flutter_xupdate#1]
如题：能不能让用户自己定义json格式或者让用户直接传json就好了，
让用户自己传json进去，那用户就可以把后台返回的字段包装成api想要的样子。

**Comment by xuexiangjys** [comment]
这个完全是可以的,后面我会陆续开放

**Comment by 5454267364** [comment]
请问您打算什么时候什么时候开放这个功能，如果久的话，那我就自己实现一下就好了

**Comment by xuexiangjys** [comment]
大概这两天吧

**Comment by 5454267364** [comment]
好的，感谢🙏

**Comment by xuexiangjys** [comment]
功能已经完成了,就是家里的翻墙工具不起作用了,还没发布到`https://pub.dev/`上去:

0e136cbffeac81c36ee78f32b69069c119e0eb0a
