### ISSUE TITLE
android授权storage权限后，无法下载，提示权限不足

### ISSUE THREAD

**Issue by superwei629** [xuexiangjys/flutter_xupdate#10]
![image](https://user-images.githubusercontent.com/51434982/83097118-ea736580-a0d9-11ea-932d-fc6011ec363e.png)
请问怎么回事?

**Comment by superwei629** [comment]
android版本10

**Comment by xuexiangjys** [comment]
flutter插件我貌似并没有开放设置下载缓存路径的api吧

**Comment by superwei629** [comment]
![333](https://user-images.githubusercontent.com/51434982/83107549-10583480-a0f1-11ea-8446-ca547d0de4e7.jpg)

我配置了    uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" 
但是实际在安装过程中只显示了两个权限，感觉是这个问题，请问怎么解决呢

**Comment by xuexiangjys** [comment]
现在问题是，我没有开放设置下载缓存路径的api，你是怎么设置下载的路径是Download的？？？

**Comment by xuexiangjys** [comment]
如果一定要在Download下载,可以设置兼容模式:
在manifest中配置
```
    <application
        android:requestLegacyExternalStorage="true">
    </application>

```
