### ISSUE TITLE
开始检查版本信息... 后无任何响应

### ISSUE THREAD

**Issue by BrinedFish0222** [xuexiangjys/flutter_xupdate#105]
版本：2.0.4

描述：执行到【开始检查版本信息... 】就无任何响应了。

日志：
D/[XUpdate]( 3724): XUpdate.update()启动:XUpdate{mUpdateUrl='http://localhost:8080/test', mParams={appKey=com.chaotou.iquant.iquant, versionCode=1}, mApkCacheDir='/storage/emulated/0/Android/data/com.chaotou.iquant.iquant/cache/xupdate', mIsWifiOnly=false, mIsGet=true, mIsAutoMode=false}
D/[XUpdate]( 3724): 开始检查版本信息...

代码：
  /// 检查app更新
  void _checkUpdateDefault() async {
    String updateUrl = await _appUpdateController.getAppUpdateUrl();
    LogUtil.getInstance().debug('app更新地址：$updateUrl');
    FlutterXUpdate.checkUpdate(url: updateUrl);
  }

**Comment by xuexiangjys** [comment]
你是来搞笑的吗，你连不上服务器也跑来问？
