### ISSUE TITLE
--split-per-abi参数打包无法弹窗

### ISSUE THREAD

**Issue by lsdlh** [xuexiangjys/flutter_xupdate#106]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[集成指南](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/flutter_xupdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
打包添加--split-per-abi参数出来的包没有弹窗

**使用的flutter_xupdate版本（必填）**
3.0.0

**如何重现（必填）**
 FlutterXUpdate.checkUpdate(url: "", supportBackgroundUpdate: true);

**期望的效果**
弹窗

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 小米12]
 - Android版本: [e.g. Android 13.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**Comment by xuexiangjys** [comment]
--split-per-abi 会修改打出来包的versionCode，从而导致版本判断错乱，建议不要使用这个命令：
https://blog.csdn.net/u013491829/article/details/122436435

**Comment by lsdlh** [comment]
不使用--split-per-abi命令，build.gradle里配置include
