### ISSUE TITLE
如果修改默认文字？

### ISSUE THREAD

**Issue by JakeGi** [xuexiangjys/flutter_xupdate#108]
弹框中的 “升级”，“新版本大小”，“是否升级到”， 这些文案怎么修改啊

**Comment by xuexiangjys** [comment]
需要从原生端进行修改, 重写覆盖对应的资源:
升级 -> xupdate_lab_update
新版本大小 -> xupdate_lab_new_version_size
是否升级到 -> xupdate_lab_ready_update

[xupdate-lib/src/main/res/values-zh-rCN/xupdate_strings.xml](https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/res/values-zh-rCN/xupdate_strings.xml)
