### ISSUE TITLE
权限相关

### ISSUE THREAD

**Issue by LegendaryMystic** [xuexiangjys/flutter_xupdate#12]
既然如此，那就有空加上写文件权限申请被拒绝的，回调抛出来吧，因为如果点升级申请权限的时候被拒绝了并且勾选了不在询问，那下次点击就没有反应了

**Comment by xuexiangjys** [comment]
我觉得吧,既然用户都不辞幸苦地勾选了不再询问,并且拒绝了权限申请,那你即使抛回来有能做什么呢,做软件的一定要做得如此流氓吗?

**Comment by xuexiangjys** [comment]
如果一定要加,麻烦按照模版填写,写明你的目的和理由

**Comment by LegendaryMystic** [comment]
抛回来，可以提示他去授权啊，或者跳到设置授权啊，哪有说要流氓。。。
看到你说欢迎盖楼的啊，理由就是这些咯；
哦，还有  问题里的  flutter build apk 打包方法不生效的原因 不是什么混淆的原因，是因为flutter build apk 默认开启了R8压缩的原因；

**Comment by LegendaryMystic** [comment]
没说一定要加哦，感觉整的好像我在给你添麻烦，你说的欢迎盖楼完善，才随手提的，看你个人时间吧，我是觉得目前还没人写这么完整的一套东西，看到你还给了RN 和  flutter 的 插件， 还有系统对应的前后端，能把你这个库完善起来，还是不错的；要反过来说的话，这个东西，无论是在原生处理，或者flutter channel调原生， 还是纯flutter上写都不算太难，你若觉得我是在无理伸手，大可无视

**Comment by xuexiangjys** [comment]
真搞不明白,模版写在那不用,一天到晚的提个问题整的像茶话会似的,能不能专业点?
我是花费自己业余的时间在维护项目,完全公益性质的,一个人维护十多个项目,平时工作也是忙得一笔,要是人人都像你这样提个问题跟玩似的,说句不好听的,我完全可以直接删掉.
模版只是为了提高问题提出的质量,节约大家的时间,真不知道你的怨气从哪来的

**Comment by LegendaryMystic** [comment]
怨气都来了，简直了，还茶话会呢，不知道你是看都没看还是怎样，我没觉得我说话的语气态度有何不妥，我看你是忙不过来了，当我说了一堆废话吧，就此删了吧，谢谢！

**Comment by LegendaryMystic** [comment]
回头瞅了一眼，好像并没有配issue_template吧，咄咄逼人地有点莫名其妙吧
