### ISSUE TITLE
关于传入对象下载时 下载进度条不更新的问题

### ISSUE THREAD

**Issue by lgj860123** [xuexiangjys/flutter_xupdate#13]
**下载进度条不更新的问题**
我在使用你这个插件的时候 用的版本是 flutter_xupdate: ^0.0.3，下载方法是使用FlutterXUpdate.updateByInfo(updateEntity: customParseJson(urlJson));  点击升级，如果没有权限，就弹出权限提示对话框，后面再点击升级，就出现有进度条，下载过程中进度条一直显示是0%。

**flutter_xupdate: ^0.0.3**

**点击对话框中的升级按钮**
重现的步骤:
点击更新对话中的升级按钮

**期望的效果**
能够看到进度条的百分比和进度都有更新。

 @**截图**
 `void showUploadDialog(AppVersionEntity appVersionEntity,bool isForce){
    Map<String,dynamic> data = new Map();
    data['hasUpdate'] = true;
    data['isForce'] = isForce;
    data['versionCode'] = 2;
    data['versionName'] = '${appVersionEntity.version}';
    data['updateLog'] = '${appVersionEntity.modifyContent}';
    data['apkUrl'] = '${appVersionEntity.androidDownUrl}';
    data['apkSize'] = 4096;
    String urlJson = json.encode(data);

    FlutterXUpdate.updateByInfo(updateEntity: customParseJson(urlJson));
  }`

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [魅族pro6]
 - Android版本: [e.g. Android 7.1.1]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
具体可参考下面的问题，这个和权限无关
https://github.com/xuexiangjys/XUpdate/issues/6

**Comment by lgj860123** [comment]
问题已经解决了， 我用的是传入对象的模式下载的，是应用版本号的原因   后台版本号为1.0.xx这样的就出现我说的能下载，但是进度条不更新的问题，后面叫后台把返回的版本号改为:1.0.x就可以更新下载进度条了，  但是有发现了一个新的问题，就是我传入appInfo对象的时候  已经设置了强制更新  点击弹窗中的关闭按钮还是可以关闭，这个问题怎么解决呢？

**Comment by xuexiangjys** [comment]
既然设置了强制更新是不可能有关闭按钮的

**Comment by xuexiangjys** [comment]
需要提醒你的一点就是,如果设置了强制更新,是不可以设置可以忽略版本的.否则强制更新不会生效

**Comment by cyd814** [comment]
我是1.0.X，也是一样的问题，进度条停在0%。昨天还可以的，还没找到原因。
