### ISSUE TITLE
使用flutter-boost的工程，报错3001，activity已被销毁！

### ISSUE THREAD

**Issue by songjhh** [xuexiangjys/flutter_xupdate#15]
使用flutter-boost的混合工程，在使用checkUpdate方法后，报错
`{code: 3001, detailMsg: Code:3001, msg:提示失败：activity已被销毁！, message: 提示失败：activity已被销毁！}`

**Comment by xuexiangjys** [comment]
你这种情况可能和flutter-boost这个插件的使用有关,方便的话,可以提供一个测试工程给我试试

**Comment by songjhh** [comment]
[Flutter-Boost](https://github.com/alibaba/flutter_boost)
里面有example例子，可以直接跑

**Comment by xuexiangjys** [comment]
![image](https://user-images.githubusercontent.com/15059629/86623419-26142000-bff4-11ea-9f70-e0ed82cb5e11.png)
我试过了,并没有出现任何问题,我觉得你还是使用的方式有问题
