### ISSUE TITLE
Code:5000, msg:安装APK失败！(apk文件校验不通过！)呢

### ISSUE THREAD

**Issue by dancheng99** [xuexiangjys/flutter_xupdate#16]
certutil -hashfile 2.apk 命令生成的md5 , 还是报Code:5000 
还有就是size 也会验证吗? 是填大小还是占用磁盘空间大小

**Comment by xuexiangjys** [comment]
不会MD5加密麻烦下载工具获取：
https://github.com/xuexiangjys/XUpdate#demo%E4%B8%8B%E8%BD%BD

**Comment by dancheng99** [comment]
> 不会MD5加密麻烦下载工具获取：
> https://github.com/xuexiangjys/XUpdate#demo%E4%B8%8B%E8%BD%BD



> 不会MD5加密麻烦下载工具获取：
> https://github.com/xuexiangjys/XUpdate#demo%E4%B8%8B%E8%BD%BD

你好 请问一下 点击忽略的版本 我想取消忽略 怎么弄 忽略的版本 是记录在哪的?

**Comment by xuexiangjys** [comment]
不可以，忽略就是忽略

**Comment by michael712520** [comment]
使用工具获取不到md5的值
