### ISSUE TITLE
设置themeColor 文字颜色不能设置

### ISSUE THREAD

**Issue by hujian1031** [xuexiangjys/flutter_xupdate#18]
设置themeColor颜色后，更新按钮的文字默认为黑色，不能设置

**Comment by xuexiangjys** [comment]
谁告诉你themeColor是按钮的颜色了？

**Comment by xuexiangjys** [comment]
themeColor是进度条和按钮背景的颜色，按钮文字的颜色并没有对应的api

**Comment by hujian1031** [comment]
能否提供个设置字体颜色的api，因为设置themeColor后，按钮默认黑色字体太丑了，

**Comment by xuexiangjys** [comment]
加是可以加，不过比较麻烦，得排期
