### ISSUE TITLE
大家还希望flutter_xupdate提供哪些功能？欢迎大家盖楼。

### ISSUE THREAD

**Issue by xuexiangjys** [xuexiangjys/flutter_xupdate#2]
建议最好写详细一点，有好的建议的话，可以考虑加入到开发计划中，flutter_xupdate中已有的内容就不要提了

**Comment by 33kuai** [comment]
大神那个火箭界面在哪里能改呢？

**Comment by xuexiangjys** [comment]
> 大神那个火箭界面在哪里能改呢？

后续会开放接口,目前是先满足基础需求的版本

**Comment by zhangweiwei0326** [comment]
ios也需要弹窗提示更新，希望弹窗可共用，目前这样ios升级提示还需要单独去写，点击更新直接跳转appstore 就好了

**Comment by xuexiangjys** [comment]
> ios也需要弹窗提示更新，希望弹窗可共用，目前这样ios升级提示还需要单独去写，点击更新直接跳转appstore 就好了

iOS端的实现后面会做的

**Comment by li305263** [comment]
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release

        }
    }

以后可以支持 压缩代码更删除无用资源吗

**Comment by xuexiangjys** [comment]
> buildTypes {
> release {
> minifyEnabled true
> shrinkResources true
> signingConfig signingConfigs.release
> 
> ```
>     }
> }
> ```
> 
> 以后可以支持 压缩代码更删除无用资源吗

建议不要使用`flutter build apk --release`进行打包，不设置`minifyEnabled false`会有问题。
最直接的方法就是进入到cd到android目录下，使用android的原生打包方式进行打包。例如如下命令：
```
./gradlew assembleRelease
```

**Comment by aboutmydreams** [comment]
希望可以讲解下校验问题，我使用了签名的md5，但是仍然错误：{detailMsg: Code:5000, msg:安装APK失败！(apk文件校验不通过！), message: 安装APK失败！(apk文件校验不通过！), code: 5000}

（安卓app的安装过程中，md5是必要的吗）

**Comment by xuexiangjys** [comment]
> 希望可以讲解下校验问题，我使用了签名的md5，但是仍然错误：{detailMsg: Code:5000, msg:安装APK失败！(apk文件校验不通过！), message: 安装APK失败！(apk文件校验不通过！), code: 5000}
> 
> （安卓app的安装过程中，md5是必要的吗）

MD5是对APK进行MD5加密后的值，不是签名的MD5，还不明白的话可以看源码：
https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/java/com/xuexiang/xupdate/proxy/impl/DefaultFileEncryptor.java

**Comment by aboutmydreams** [comment]
原来是这样，感谢！

**Comment by Maclaon** [comment]
- 能增加下载缓存机制吗？
- App内部更新，更新完毕后，提示重启App完成更新？

**Comment by jaimyu** [comment]
debug环境可能正常更新， 以release模式运行提示“已是最新版本”。 直接打包： flutter build apk

**Comment by xuexiangjys** [comment]
> debug环境可能正常更新， 以release模式运行提示“已是最新版本”。 直接打包： flutter build apk

这里不是提问题的地方

**Comment by xuexiangjys** [comment]
> debug环境可能正常更新， 以release模式运行提示“已是最新版本”。 直接打包： flutter build apk

这个在最新的flutter版本中貌似已经被修复了

**Comment by wangjinbiao1985** [comment]
静默安装更新完毕后，如何自动重启app？

**Comment by ylic** [comment]
关于多语言支持的问题？
ModifyContent的内容接口可以根据用户的post请求返回对应的语言。但是升级界面的其它文字如何支持多语言。比如“是否升级到xxxx版本”，“新版大小”，“升级”，这些文字。
如果能提供一个自定义语言的接口就好了。

**Comment by xuexiangjys** [comment]
> 关于多语言支持的问题？
> ModifyContent的内容接口可以根据用户的post请求返回对应的语言。但是升级界面的其它文字如何支持多语言。比如“是否升级到xxxx版本”，“新版大小”，“升级”，这些文字。
> 如果能提供一个自定义语言的接口就好了。

项目中的界面使用的是native页面,怕是不能提供这个接口,你可以使用native的方式实现国际化

**Comment by ylic** [comment]
能否把 XUpdate的下面三个功能，开放出来。
1、文件加密校验
2、XUpdate的下载器功能
3、XUpdate的APK安装的功能

有了这三个功能，就可以自己写弹窗了。

**Comment by xuexiangjys** [comment]
> 能否把 XUpdate的下面三个功能，开放出来。
> 1、文件加密校验
> 2、XUpdate的下载器功能
> 3、XUpdate的APK安装的功能
> 
> 有了这三个功能，就可以自己写弹窗了。

想自己写弹窗?我建议你还是不要使用本库好了,这样太麻烦了,没必要. 你可以使用下面的方案做参考:
1.使用package_info插件获取当前应用的版本信息
2.使用dio插件进行网络请求获取最新版本信息
3.使用flutter_downloader插件下载最新APP并安装

**Comment by yinzhonghua** [comment]
> debug环境可能正常更新， 以release模式运行提示“已是最新版本”。 直接打包： flutter build apk

同样问题，dubug正常，一打正式包就不行了，求解决
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale zh-CN)
    • Flutter version 1.17.5 at D:\DEV\sdk\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\DEV\sdk\android
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\DEV\sdk\android
    • Java binary at: D:\DEV\ide\as4\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at D:\DEV\ide\as4
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM G9730                  • R28M22M11EW   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 6.0 (API 23) (emulator)

**Comment by xuexiangjys** [comment]
麻烦多看文档,谢谢:
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0

**Comment by lion-not-swim** [comment]
添加 点击取消下载的回调事件

**Comment by xuexiangjys** [comment]
> 添加 点击取消下载的回调事件

4002错误码就是取消下载

**Comment by caizetong** [comment]
如果已经是最新版本，可否有返回信息，提示已经是最新版本。

**Comment by xuexiangjys** [comment]
> 如果已经是最新版本，可否有返回信息，提示已经是最新版本。

2004错误码就是无最新版本

**Comment by caizetong** [comment]
但是还有一个问题，我无法知道这个属于系统自动检查更新的错误码还是用户手动点击"检查更新"后的错误码，用户手动点击后要给一个提示。系统自动检测的话不需要，为此需要一个区分。如果能在checkUpdate返回一下就方便些。

**Comment by caizetong** [comment]
不过这个也有解决方案就是每次调用checkUpdate前设置一次setErrorHandler，尽量保证处理这次更新的错误信息。

**Comment by xuexiangjys** [comment]
> 不过这个也有解决方案就是每次调用checkUpdate前设置一次setErrorHandler，尽量保证处理这次更新的错误信息。

原生库也是这么处理的

**Comment by Kimxu** [comment]
halo，从Android跟到Flutter，功能做的很好，代码写的不错，给你个赞，另外请教个问题，下载进度，我这边服务器没时间搞，所以下载的时候不显示进度，请问能不能提供个方法，隐藏进度条，显示 “下载中...“ 这三个字

**Comment by 1Ezreal** [comment]
希望文字内容可以自己设置，如是否升级到、升级，后台下载，正在下载等，方便修改和国际化
总的来说很好用，比flutter 一些插件的兼容好很多，但是项目五种语言没法国际化

**Comment by Panxiaozhu** [comment]
希望可以支持后台下载

**Comment by Panxiaozhu** [comment]
> 
> 
> > buildTypes {
> > release {
> > minifyEnabled true
> > shrinkResources true
> > signingConfig signingConfigs.release
> > ```
> >     }
> > }
> > ```
> > 
> > 
> > 以后可以支持 压缩代码更删除无用资源吗
> 
> 建议不要使用`flutter build apk --release`进行打包，不设置`minifyEnabled false`会有问题。
> 最直接的方法就是进入到cd到android目录下，使用android的原生打包方式进行打包。例如如下命令：
> 
> ```
> ./gradlew assembleRelease
> ```

 的确是，但是用./gradlew assembleRelease 打包体积大好多，.so库怎么只留v7a?

**Comment by xuexiangjys** [comment]
> 希望可以支持后台下载

supportBackgroundUpdate 字段设置为true

**Comment by Panxiaozhu** [comment]
> 
> 
> > 希望可以支持后台下载
> 
> supportBackgroundUpdate 字段设置为true

thanks

**Comment by niumenglin** [comment]
下载地址重定向302错误，Android端代码需要兼容一下哈？

**Comment by SouMte-W** [comment]
请问我的flutter更新下载完成后显示安装apk失败是为什么呢  不是md5的问题

**Comment by Panxiaozhu** [comment]
那是apk问题吧

**Comment by SouMte-W** [comment]
可是那个apk手动可以安装成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuexiangjys/flutter_xupdate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午4:08
收件人:&nbsp;"xuexiangjys/flutter_xupdate"<flutter_xupdate@noreply.github.com&gt;;
抄送:&nbsp;"(๑• . •๑)"<1005740558@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuexiangjys/flutter_xupdate] 大家还希望flutter_xupdate提供哪些功能？欢迎大家盖楼。 (#2)





 
那是apk问题吧

**Comment by SouMte-W** [comment]
不是&nbsp; 是进度条完成了以后&nbsp; 显示安装apk失败 我看文件管理里根本就没有下载下来apk




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuexiangjys/flutter_xupdate"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午4:08
收件人:&nbsp;"xuexiangjys/flutter_xupdate"<flutter_xupdate@noreply.github.com&gt;;
抄送:&nbsp;"(๑• . •๑)"<1005740558@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuexiangjys/flutter_xupdate] 大家还希望flutter_xupdate提供哪些功能？欢迎大家盖楼。 (#2)





 
那是apk问题吧

**Comment by SouMte-W** [comment]
找到原因了 是MD5的问题 打扰了

**Comment by xuexiangjys** [comment]
> 找到原因了 是MD5的问题 打扰了

请不要在这里讨论问题,要讨论请到
[discussions](https://github.com/xuexiangjys/flutter_xupdate/discussions)里去讨论

**Comment by wjx1018960145** [comment]
为什么一直返回无最新版本 怎么修改版本判断  返回了有新的版本json数据 还是提示无最新的版本

**Comment by gitsprouts** [comment]
直接传入UpdateEntity进行更新，怎么设置强制更新? @xuexiangjys

**Comment by xuexiangjys** [comment]
> 直接传入UpdateEntity进行更新，怎么设置强制更新? @xuexiangjys

isForce设置成true啊,不看文档的嘛,不要在这里问问题,ok?

**Comment by gitsprouts** [comment]
> > 直接传入UpdateEntity进行更新，怎么设置强制更新? @xuexiangjys
> 
> isForce设置成true啊,不看文档的嘛,不要在这里问问题,ok?

不好意思，我设置了不行。

**Comment by GGSDDUAY** [comment]
你好，我提交bug一直被自动关闭，我已经star这个项目了，还是被关闭，麻烦你看一下。谢谢
https://github.com/xuexiangjys/flutter_xupdate/issues/32#issue-817106224

**Comment by gitsprouts** [comment]
更新的时候，后台退出app，还能保持安装进程。

**Comment by gitsprouts** [comment]
点击更新的时候，如果后台退出APP后，还能保持下载并更新。

**Comment by gitsprouts** [comment]
> 建议最好写详细一点，有好的建议的话，可以考虑加入到开发计划中，flutter_xupdate中已有的内容就不要提了

点击更新的时候，如果后台退出APP后，还能保持下载并更新，那就更厉害了。

**Comment by the6nnoo** [comment]
> > 建议最好写详细一点，有好的建议的话，可以考虑加入到开发计划中，flutter_xupdate中已有的内容就不要提了
> 
> 点击更新的时候，如果后台退出APP后，还能保持下载并更新，那就更厉害了。

你咋不上天呢

**Comment by gitsprouts** [comment]
> > > 建议最好写详细一点，有好的建议的话，可以考虑加入到开发计划中，flutter_xupdate中已有的内容就不要提了
> > 
> > 
> > 点击更新的时候，如果后台退出APP后，还能保持下载并更新，那就更厉害了。
> 
> 你咋不上天呢

无知别乱回。

**Comment by xuexiangjys** [comment]
> > > > 建议最好写详细一点，有好的建议的话，可以考虑加入到开发计划中，flutter_xupdate中已有的内容就不要提了
> > > 
> > > 
> > > 点击更新的时候，如果后台退出APP后，还能保持下载并更新，那就更厉害了。
> > 
> > 
> > 你咋不上天呢
> 
> 无知别乱回。

你的建议,我实在是不敢苟同,不过你要是真想这么做,我倒是可以给你个建议,自己重写一下下载模块,放到别的进程里面就好了

**Comment by gaoguanqi** [comment]
该升级 package_info 了，依赖时就会出错

**Comment by icofans** [comment]
null-safety support ?

**Comment by next-autumn** [comment]
null-safety 感谢！

**Comment by canyonwan** [comment]
请问什么时候可级适配flutter 2.0的空安全, 要不没法使用其他的包

**Comment by xuexiangjys** [comment]
> null-safety support ?

Supported

**Comment by gabbar1** [comment]
{code: 2004, detailMsg: Code:2004, msg:It's the latest version!, message: It's the latest version!}
我在製作發行版APK後收到此錯誤

**Comment by Andrewkz** [comment]
‘直接传入UpdateEntity进行更新提示“，这种模式下，如何去掉弹窗中忽略此版本的按钮？

**Comment by xuexiangjys** [comment]
> {code: 2004, detailMsg: Code:2004, msg:It's the latest version!, message: It's the latest version!}
> 我在製作發行版APK後收到此錯誤

https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0

**Comment by tangwei5476** [comment]
debug下显示 topImageRes的图片，release下不显示。什么个原因

**Comment by xuexiangjys** [comment]
> debug下显示 topImageRes的图片，release下不显示。什么个原因

https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0

**Comment by xuexiangjys** [comment]
由于垃圾贴太多, flutter_xupdate不再提供新功能的讨论.

**Comment by tangwei5476** [comment]
> > debug下显示 topImageRes的图片，release下不显示。什么个原因
> 
> https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0

白天就试过了。刚又花一个小时，试了。没一点用。算了，我自己写吧。真不靠谱

**Comment by tangwei5476** [comment]
> > debug下显示 topImageRes的图片，release下不显示。什么个原因
> 
> https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%B9%E6%A1%86%E6%A0%B7%E5%BC%8F%E7%9A%84%E9%A1%B6%E9%83%A8%E5%9B%BE%E7%89%87debug%E4%B8%8B%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA%E4%BD%86%E6%98%AF%E5%9C%A8release%E4%B8%8B%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA

作者，我道歉。我弱鸡。早上看到你删了我消极言论。我在回头看答案，已经给出来解决方法了。不用生我这种小垃圾的气。0_<  
  另外，弱弱的再提一个小小建议。如果图片没找到，可以给个默认图片。或者图片的名称是空字符串，那就不展示顶部的图片。作者大人大量，大神不用理会我这种小菜鸡的话。再次抱歉
