### ISSUE TITLE
打包bug

### ISSUE THREAD

**Issue by Panxiaozhu** [xuexiangjys/flutter_xupdate#20]
大佬，使用flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi打包的apk，头部自定义图片会加载失败，更新弹窗显示一条空白条

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0
