### ISSUE TITLE
设置topImageRes之后底部关闭按钮显示不全

### ISSUE THREAD

**Issue by GGSDDUAY** [xuexiangjys/flutter_xupdate#30]
**问题描述（必填）**
`使用自定义更新图片之后，手机字体和显示大小设置为标准（或默认）情况下，更新提示底部的关闭按钮无法完全显示。详情见截图。`

**使用的flutter_xupdate版本（必填）**

`flutter_xupdate-1.0.2`

**如何重现（必填）**
重现的步骤:

`无具体步骤。`

**期望的效果**

`底部关闭按钮可以正常显示。`

**截图**

```
   FlutterXUpdate.updateByInfo(topImageRes: 'bg_update_top1',updateEntity: updateEntity, themeColor: themeColor,buttonTextColor: buttonTextColor);
```

![QQ图片20210226095154](https://user-images.githubusercontent.com/10781685/109243895-b8359680-7818-11eb-9d06-149f195ec4a1.jpg)

- 如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。
    

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [华为荣耀20 pro]
 - Android版本: [Android 10.0]
 - 设备型号 [YAL-AL10] 
 - Magic UI版本 [4.0.0]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
从来没有碰到过这种问题,可以尝试设置heightRatio属性试试
