### ISSUE TITLE
直接传入UpdateEntity进行更新提示，传入isForce: true，没有效果？

### ISSUE THREAD

**Issue by gitsprouts** [xuexiangjys/flutter_xupdate#34]
///将自定义的json内容解析为UpdateEntity实体类
  UpdateEntity customParseJson(String json) {
    AppInfo appInfo = AppInfo.fromJson(json);
    print(appInfo);
    return UpdateEntity(
        isForce: true,
        hasUpdate: appInfo.hasUpdate,
        isIgnorable: appInfo.isIgnorable,
        versionCode: appInfo.versionCode,
        versionName: appInfo.versionName,
        updateContent: appInfo.updateLog,
        downloadUrl: appInfo.apkUrl,
        apkSize: appInfo.apkSize);
  }

  String _customJson = '{"updateStatus": 2,"hasUpdate": true, "isIgnorable": true,"versionCode": 3,"versionName": "1.0.2","updateLog": "1、优化api接口。2、添加使用demo演示。3、新增自定义更新服务API接口。4、优化更新提示界面。","apkUrl": "https://down.qq.com/qqweb/QQ_1/android_apk/Android_8.5.0.5025_537066738.apk","apkSize": 4096}';

  ///直接传入UpdateEntity进行更新提示
  void checkUpdateSupportBackground() {
    UpdateEntity updateEntity = customParseJson(_customJson);
    FlutterXUpdate.updateByInfo(updateEntity: updateEntity);
  }

大家碰到过嘛?

**Comment by xuexiangjys** [comment]
设置了isForce为true了之后,是不可以设置isIgnorable为true的,否则isForce不会生效,知道不?
你自己想一下,强制版本更新的,可以忽略吗???
