### ISSUE TITLE
Caused by: android.view.InflateException: Binary XML file line #28 in com.example.myapp:layout/xupdate_dialog_update: Error inflating class 

### ISSUE THREAD

**Issue by mimicode** [xuexiangjys/flutter_xupdate#36]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[集成指南](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/flutter_xupdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**

I/[XUpdate](32372): 发现新版本:UpdateEntity{mHasUpdate=true, mIsForce=false, mIsIgnorable=false, mVersionCode=243, mVersionName='2.4.3', mUpdateContent='优化app稳定性', mDownloadEntity=DownloadEntity{mDownloadUrl='https://192.168.1.88:8080/myapp.apk', mCacheDir='/storage/emulated/0/Android/data/com.example.myapp/cache/xupdate', mMd5='3666012c0c53896146b40272895feb0c', mSize=43430, mIsShowNotification=false}, mIsSilent=false, mIsAutoInstall=true, mIUpdateHttpService=com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService@a636d1a}
W/System.err(32372): android.view.InflateException: Binary XML file line #28 in com.example.myapp:layout/xupdate_dialog_update: Binary XML file line #28 in com.example.myapp:layout/xupdate_dialog_update: Error inflating class androidx.appcompat.widget.AppCompatImageView
W/System.err(32372): Caused by: android.view.InflateException: Binary XML file line #28 in com.example.myapp:layout/xupdate_dialog_update: Error inflating class androidx.appcompat.widget.AppCompatImageView
W/System.err(32372): Caused by: java.lang.reflect.InvocationTargetException
W/System.err(32372):    at java.lang.reflect.Constructor.newInstance0(Native Method)
W/System.err(32372):    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
W/System.err(32372):    at android.view.LayoutInflater.createView(LayoutInflater.java:856)
W/System.err(32372):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
W/System.err(32372):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
W/System.err(32372):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
W/System.err(32372):    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
W/System.err(32372):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1128)
W/System.err(32372):    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
W/System.err(32372):    at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
W/System.err(32372):    at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
W/System.err(32372):    at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
W/System.err(32372):    at com.xuexiang.xupdate.widget.BaseDialog.init(BaseDialog.java:74)
W/System.err(32372):    at com.xuexiang.xupdate.widget.BaseDialog.<init>(BaseDialog.java:64)
W/System.err(32372):    at com.xuexiang.xupdate.widget.BaseDialog.<init>(BaseDialog.java:51)
W/System.err(32372):    at com.xuexiang.xupdate.widget.UpdateDialog.<init>(UpdateDialog.java:128)
W/System.err(32372):    at com.xuexiang.xupdate.widget.UpdateDialog.newInstance(UpdateDialog.java:119)
W/System.err(32372):    at com.xuexiang.flutter_xupdate.FlutterUpdatePrompter.showPrompt(FlutterUpdatePrompter.java:60)
W/System.err(32372):    at com.xuexiang.xupdate.UpdateManager.findNewVersion(UpdateManager.java:344)
W/System.err(32372):    at com.xuexiang.xupdate.utils.UpdateUtils.processUpdateEntity(UpdateUtils.java:91)
W/System.err(32372):    at com.xuexiang.xupdate.UpdateManager.update(UpdateManager.java:437)
W/System.err(32372):    at com.xuexiang.flutter_xupdate.FlutterXUpdatePlugin.updateByInfo(FlutterXUpdatePlugin.java:223)
W/System.err(32372):    at com.xuexiang.flutter_xupdate.FlutterXUpdatePlugin.onMethodCall(FlutterXUpdatePlugin.java:77)
W/System.err(32372):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(32372):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(32372):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(32372):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(32372):    at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(32372):    at android.os.Looper.loop(Looper.java:193)
W/System.err(32372):    at android.app.ActivityThread.main(ActivityThread.java:8057)
W/System.err(32372):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32372):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err(32372):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/System.err(32372): Caused by: java.lang.NoSuchMethodError: No static method saveAttributeDataForStyleable(Landroid/view/View;Landroid/content/Context;[ILandroid/util/AttributeSet;Landroid/content/res/TypedArray;II)V in class Landroidx/core/view/ViewCompat; or its super classes (declaration of 'androidx.core.view.ViewCompat' appears in /data/app/~~J990GAEsaMPPuW3k31qguQ==/com.example.myapp-sqV0hoXhein0wgprzbWIGw==/base.apk)
W/System.err(32372):    at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:51)
W/System.err(32372):    at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:79)
W/System.err(32372):    at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
W/System.err(32372):    ... 33 more

**使用的flutter_xupdate版本（必填）**

flutter_xupdate: 1.0.2  或 master

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 小米10
 - Android版本: 11
 - 设备型号  xiaomi10
 - 系统版本 miui 11

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
文档要咨询看，ok？

https://github.com/xuexiangjys/flutter_xupdate#setting-up
