### ISSUE TITLE
请问下，根据什么判断是否有新版本的？

### ISSUE THREAD

**Issue by xdnice** [xuexiangjys/flutter_xupdate#4]
我在应用中放了一个按钮，用来检测新版本，如果检测到新版本就强制升级。现在遇到的情况是，即使升级到最新版本，再点击检测新版本，会把下载的新版本再安装一遍，不知道这个该怎么解决？请指教。谢谢了！

**Comment by xuexiangjys** [comment]
默认首先是根据`UpdateStatus`字段来判断的，UpdateStatus为1是更新，2是强制更新，0不需要更新。如果需要更新的话，还会根据应用的VersionCode来进行二次判断，详细你自己去看源码。
参考如下代码:
https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/java/com/xuexiang/xupdate/proxy/impl/DefaultUpdateParser.java
