### ISSUE TITLE
> 希望能够支持压缩后的Apk，否则太大了影响用户下载

### ISSUE THREAD

**Issue by aboutmydreams** [xuexiangjys/flutter_xupdate#5]
> 你如果用的是`flutter build apk --release`命令的话，建议增加如下配置试一下:
> 
> ```
>     buildTypes {
>         release {
>             minifyEnabled false
>             shrinkResources false
>             signingConfig signingConfigs.debug
>         }
>     }
> ```
能兼容 压缩资源跟压缩代码那

_Originally posted by @li305263 in https://github.com/xuexiangjys/flutter_xupdate/issues/3#issuecomment-603121160_

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0

**Comment by aboutmydreams** [comment]
嗯嗯，但是目前大多数人是有分包需求的，使用这条命令打包，这种方式将apk缩小了近一半
但是这种情况下插件无法安装新版本
flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

**Comment by xuexiangjys** [comment]
一样的，使用原生进行打包同样也能压缩apk大小，你只需要配置ndk支持的类型也一样能达到效果。
```
        ndk {
            abiFilters "armeabi"
        }
```
