### ISSUE TITLE
release弹出框界面问题

### ISSUE THREAD

**Issue by muziri** [xuexiangjys/flutter_xupdate#52]
![image](https://user-images.githubusercontent.com/12822525/120309863-4e8dc280-c308-11eb-913f-2ded60b90876.png)

**Comment by xuexiangjys** [comment]
详细参见:
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%B9%E6%A1%86%E6%A0%B7%E5%BC%8F%E7%9A%84%E9%A1%B6%E9%83%A8%E5%9B%BE%E7%89%87debug%E4%B8%8B%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA%E4%BD%86%E6%98%AF%E5%9C%A8release%E4%B8%8B%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA
