### ISSUE TITLE
自定义弹框，release下顶部图片不显示

### ISSUE THREAD

**Issue by tangwei5476** [xuexiangjys/flutter_xupdate#53]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[集成指南](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/flutter_xupdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
使用自定义弹框样式的顶部图片，debug下正常显示。release下图片不显示

**使用的flutter_xupdate版本（必填）**
2.0.0

**如何重现（必填）**
重现的步骤:
1. 使用如下的代码 FlutterXUpdate.checkUpdate(
        url: _updateUrl,
        themeColor: '#FFFFAC5D',
        topImageRes: 'bg_update_top',
        buttonTextColor: '#FFFFFFFF');
2. 运行release版本 flutter run --release
3. 应用启动后，更新界面不显示图片
![微信图片_20210615154027](https://user-images.githubusercontent.com/47875793/122012731-1306f400-cdf0-11eb-82a8-7c27b7d5ef06.jpg)

**期望的效果**
更新界面，和debug模式下一样，正常显示图片
![微信图片_20210615154447](https://user-images.githubusercontent.com/47875793/122013327-a7715680-cdf0-11eb-8b3e-55f32d183b62.jpg)

**截图**
代码图片
![微信图片_20210615154439](https://user-images.githubusercontent.com/47875793/122013499-cec82380-cdf0-11eb-86e4-7ede79ffc72f.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [小米6]
 - Android版本: [Android 9]
 - 设备型号 [MI 6]
 - 系统版本（miui12 20.6.18）

**附加信息**
无

**Comment by xuexiangjys** [comment]
详细参见:
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%B9%E6%A1%86%E6%A0%B7%E5%BC%8F%E7%9A%84%E9%A1%B6%E9%83%A8%E5%9B%BE%E7%89%87debug%E4%B8%8B%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA%E4%BD%86%E6%98%AF%E5%9C%A8release%E4%B8%8B%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA
