### ISSUE TITLE
demo 运行的提示语跟更新按钮是英文

### ISSUE THREAD

**Issue by gitsprouts** [xuexiangjys/flutter_xupdate#55]
demo 运行的提示语跟更新按钮只有英文跟中文，是跟随系统的，能否还支持别的语言？，使用版本2.0.0。
![image](https://user-images.githubusercontent.com/10768266/124493240-fa36a080-dde7-11eb-92a3-a3ff6ae4bc10.png)

**Comment by xuexiangjys** [comment]
因为flutter_xupdate底层调用的是XUpdate原生库, 更新UI是原生写的,因此要实现多语言国际化的话,需要使用原生的国际化进行配置.

**Comment by gitsprouts** [comment]
> 因为flutter_xupdate底层调用的是XUpdate原生库, 更新UI是原生写的,因此要实现多语言国际化的话,需要使用原生的国际化进行配置.
> XUpdate原生库默认只支持英语和中文,默认是英语,跟随系统

我可以自己修改吗？给点提示。谢谢

**Comment by xuexiangjys** [comment]
自己去搜Android国际化的方式，找到对应的文字key就可以了：

具体的key可以看源码知道
https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/res/values/xupdate_strings.xml

**Comment by gitsprouts** [comment]
> 自己去搜Android国际化的方式，找到对应的文字key配置一下多语言翻译就可以了：
> 
> 具体的key可以看源码知道
> https://github.com/xuexiangjys/XUpdate/blob/master/xupdate-lib/src/main/res/values/xupdate_strings.xml

好的，多谢，我先研究下。

**Comment by cn1001wang** [comment]
没学过Android，这个xupdate_strings.xml文件应该放在哪个文件夹下
