### ISSUE TITLE
Pixel 4 这个版本的模拟器能弹出窗口，但是不能完成更新安装

### ISSUE THREAD

**Issue by gitsprouts** [xuexiangjys/flutter_xupdate#56]
Pixel 4 这个版本的模拟器能弹出窗口，但是不能完成更新安装，提示”未安装应用“，后台也没打印错误信息，使用版本2.0.0。
模拟器信息：
![image](https://user-images.githubusercontent.com/10768266/124692538-55fc4900-df10-11eb-941f-1dbd1642ce03.png)
安装提示信息：
![image](https://user-images.githubusercontent.com/10768266/124693622-5b5a9300-df12-11eb-8924-09aa40ec4d41.png)

**Comment by xuexiangjys** [comment]
麻烦多看看文档再问行不行?
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2
提issue有这么随便的嘛?一有问题就提issue,提个issue连个问题都说不清楚,也不按照issue模版来填写有用的信息,你想干什么?

**Comment by gitsprouts** [comment]
> 麻烦多看看文档再问行不行?
> https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2
> 提issue有这么随便的嘛?一有问题就提issue,提个issue连个问题都说不清楚,也不按照issue模版来填写有用的信息,你想干什么?

大兄弟，首先谢谢你的开源工具，但是竟然开源就也要有点开源精神，大家都是刚入门学习，也有看漏或者是不懂的地方，有时候就是不知道问题在哪？才不懂说清楚，你看到有时间就给个回复，或者提示，这也是基本的吧？但是你这种回复说我想干什么？我是觉得说那么多不如来个提示是吧？

**Comment by xuexiangjys** [comment]
> > 麻烦多看看文档再问行不行?
> > https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2
> > 提issue有这么随便的嘛?一有问题就提issue,提个issue连个问题都说不清楚,也不按照issue模版来填写有用的信息,你想干什么?
> 
> 大兄弟，首先谢谢你的开源工具，但是竟然开源就也要有点开源精神，大家都是刚入门学习，也有看漏或者是不懂的地方，有时候就是不知道问题在哪？才不懂说清楚，你看到有时间就给个回复，或者提示，这也是基本的吧？但是你这种回复说我想干什么？我是觉得说那么多不如来个提示是吧？

不想骂人，文档写得那么仔细，还有视频教程，不看，天天跑来issue里面烦人，我欠你的吗？

**Comment by xuexiangjys** [comment]
> > 麻烦多看看文档再问行不行?
> > https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2
> > 提issue有这么随便的嘛?一有问题就提issue,提个issue连个问题都说不清楚,也不按照issue模版来填写有用的信息,你想干什么?
> 
> 大兄弟，首先谢谢你的开源工具，但是竟然开源就也要有点开源精神，大家都是刚入门学习，也有看漏或者是不懂的地方，有时候就是不知道问题在哪？才不懂说清楚，你看到有时间就给个回复，或者提示，这也是基本的吧？但是你这种回复说我想干什么？我是觉得说那么多不如来个提示是吧？

和我谈开源精神，你开源了什么？你有资格说我嘛？我开源了30+个项目，你开源了什么？
要是人人都像你这样乱提issue，我TM还要休息了吗？做你们的保姆，服侍你们一辈子吗？
再说了，我没有给你提示吗，文档写了那么清楚，不看怪我喽？真不想骂人！
