### ISSUE TITLE
查询失败：解析Json错误！

### ISSUE THREAD

**Issue by gmingxin** [xuexiangjys/flutter_xupdate#57]
.flutter_v1_example/cache/xupdate', mMd5='89341b4e1b484585252b91967b907b07', mSize=81000, mIsShowNotification=false}, mIsSilent=false, mIsAutoInstall=true, mIUpdateHttpService=com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService@dc6aaa}
E/ThemeUtils(14484): View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(14484): View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/System.err(14484): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
W/System.err(14484): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
W/System.err(14484): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
W/System.err(14484): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:684)
W/System.err(14484): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:100)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.BaseDialog.init(BaseDialog.java:79)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.BaseDialog.init(BaseDialog.java:75)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.BaseDialog.<init>(BaseDialog.java:64)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.BaseDialog.<init>(BaseDialog.java:51)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.UpdateDialog.<init>(UpdateDialog.java:128)
W/System.err(14484): 	at com.xuexiang.xupdate.widget.UpdateDialog.newInstance(UpdateDialog.java:119)
W/System.err(14484): 	at com.xuexiang.flutter_xupdate.FlutterUpdatePrompter.showPrompt(FlutterUpdatePrompter.java:60)
W/System.err(14484): 	at com.xuexiang.xupdate.UpdateManager.findNewVersion(UpdateManager.java:344)
W/System.err(14484): 	at com.xuexiang.xupdate.utils.UpdateUtils.processUpdateEntity(UpdateUtils.java:92)
W/System.err(14484): 	at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.processCheckResult(DefaultUpdateChecker.java:137)
W/System.err(14484): 	at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.onCheckSuccess(DefaultUpdateChecker.java:102)
W/System.err(14484): 	at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.access$000(DefaultUpdateChecker.java:46)
W/System.err(14484): 	at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker$1.onSuccess(DefaultUpdateChecker.java:65)
W/System.err(14484): 	at com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService$1.onResponse(OKHttpUpdateHttpService.java:82)
W/System.err(14484): 	at com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService$1.onResponse(OKHttpUpdateHttpService.java:74)
W/System.err(14484): 	at com.zhy.http.okhttp.OkHttpUtils$3.run(OkHttpUtils.java:186)
W/System.err(14484): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(14484): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(14484): 	at android.os.Looper.loop(Looper.java:263)
W/System.err(14484): 	at android.app.ActivityThread.main(ActivityThread.java:7810)
W/System.err(14484): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(14484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
I/flutter (14484): {code: 2006, detailMsg: Code:2006, msg:查询失败：解析Json错误！(You need to use a Theme.AppCompat theme (or descendant) with this activity.), message: 查询失败：解析Json错误！(You need to use a Theme.AppCompat theme (or descendant) with this activity.)}

**Comment by xuexiangjys** [comment]
修改Android项目的主题为AppCompat主题的这步被你吃了？
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97#android%E8%AE%BE%E7%BD%AE

**Comment by gmingxin** [comment]
修改了，在小米华为等机型上都能正常提示下载并安装，在华硕ROG phone5机型上就提示这个错误。

**Comment by xuexiangjys** [comment]
(⊙﹏⊙)，华硕ROG phone5机型 这什么机型啊...什么破rom
你自己修改插件FlutterUpdatePrompter试一下吧，主要修改UpdateDialog这个类。
https://github.com/xuexiangjys/flutter_xupdate/blob/master/android/src/main/java/com/xuexiang/flutter_xupdate/FlutterUpdatePrompter.java

**Comment by gmingxin** [comment]
好谢谢
