### ISSUE TITLE
在Flutter版本1.22.3项目中引入flutter_xupdate版本1.0.2出现编译异常

### ISSUE THREAD

**Issue by UniKylin** [xuexiangjys/flutter_xupdate#58]
![image](https://user-images.githubusercontent.com/10378778/125592511-9b2f4aea-8f7f-4a80-b721-2d27799f5abc.png)

```
flutter_xupdate: ^1.0.2
```

开发环境中出现异常，引入插件后初始化如下：
```
void initState() {
    super.initState();
    FlutterXUpdate.init(debug: true);
  }
```
进行编译调试就开始报错了，麻烦处理下，谢谢

**Comment by xuexiangjys** [comment]
你自己的网络问题,依赖没有下下来

**Comment by UniKylin** [comment]
> 下来

我调整下姿势
