### ISSUE TITLE
按照官方demo传递的更新提示,没有换行

### ISSUE THREAD

**Issue by bingw002** [xuexiangjys/flutter_xupdate#62]
**问题描述（必填）**
按照官方demo传递的更新提示,没有换行

**使用的flutter_xupdate版本（必填）**
当前最新的2.0.1

**如何重现（必填）**
按照官方步骤,使用FlutterXUpdate.updateByInfo直接更新,更新动作正常,只是界面显示不对.

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
![微信图片_20210914100746](https://user-images.githubusercontent.com/61919065/133183094-36e8138e-19c7-4e91-b574-b8aff4b8e767.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
来自模拟器
 - 设备名: [Google Nexus6]
 - Android版本: Android 8.0]
 - 设备型号[Google Nexus6]
 - 系统版本（Google标准的Android 8.0,SDK是28）

**附加信息**
语言为英文

**Comment by xuexiangjys** [comment]
你的内容不对，缺少转义字符，ok？
