### ISSUE TITLE
您好，请问一下有没有"点击"升级按钮后的回调事件

### ISSUE THREAD

**Issue by hg542006810** [xuexiangjys/flutter_xupdate#64]
**问题描述（必填）**
需求：需要在点击"升级"按钮后，调用后端升级数量 + 1的接口
我在文档里没有找到类似的回调事件

**使用的flutter_xupdate版本（必填）**
2.0.1

**期望的效果**
希望有一个点击"升级"按钮的回调

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 华为P20
 - Android版本: Android10

**Comment by xuexiangjys** [comment]
这块暂时没有

**Comment by hg542006810** [comment]
有什么扩展的方法吗？
