### ISSUE TITLE
作者你好,关于出现release包通过已知的方法打包后还是无法正常更新的问题的解决方法

### ISSUE THREAD

**Issue by gobuilderlei** [xuexiangjys/flutter_xupdate#68]
因为flutter默认自带混淆,所以在打包的时候会使用R8进行打包.
> Task :app:minifyReleaseWithR8 这里会提示.

需要在 /andriod/app/build.gradle 中加入  minifyEnabled false //删除无用代码
 buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            shrinkResources false
            minifyEnabled false //删除无用代码
            signingConfig signingConfigs.release
        }
         debug {
            signingConfig signingConfigs.debug
        }
    }

这样关闭自带混淆,然后再通过原生打包  ./gradlew assembleRelease命令就可以了.

**Comment by xuexiangjys** [comment]
关闭R8混淆
