### ISSUE TITLE
Could not resolve com.github.xuexiangjys:XUpdate:2.0.7.

### ISSUE THREAD

**Issue by SinoMiles** [xuexiangjys/flutter_xupdate#69]
![image](https://user-images.githubusercontent.com/9588025/144018394-a2056b4f-88e7-4753-ab87-24b2dcac566f.png)

Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.xuexiangjys:XUpdate:2.0.7.
quired by:
         project :app > project :flutter_xupdate
      > Could not resolve com.github.xuexiangjys:XUpdate:2.0.7.
         > Could not get resource 'https://dl.bintray.com/umsdk/release/com/github/xuexiangjys/XUpdate/2.0.7/XUpdate-2.0.7.pom'.
            > Could not HEAD 'https://dl.bintray.com/umsdk/release/com/github/xuexiangjys/XUpdate/2.0.7/XUpdate-2.0.7.pom'. Received status code 502 from server: Bad Gateway

**Comment by xuexiangjys** [comment]
???

**Comment by xuexiangjys** [comment]
XUpdate是发布在jitpack上的,你整https://dl.bintray.com/umsdk/release/是什么意思,你仓库配置的不对
