### ISSUE TITLE
请问下，啥时候能提供ios的更新？

### ISSUE THREAD

**Issue by xdnice** [xuexiangjys/flutter_xupdate#7]
不知道啥时候能提供ios的更新，苹果商店的应用好说，可以直接跳转到苹果的应用商店，像企业内部应用的APP，就不能发布到应用商店，只能利用类似的功能进行升级了。

**Comment by xuexiangjys** [comment]
我对ios端不是很熟,还需要找段时间研究一下ios的应用内升级

**Comment by kaigeLove** [comment]
ios更新跳到App Store不就好了

**Comment by xuexiangjys** [comment]
具体可参考:
https://github.com/xuexiangjys/flutter_app_update_example
