### ISSUE TITLE
调试模式能正常识别新版本，但是打了正式包之后，一直提示”已是最新版本!“

### ISSUE THREAD

**Issue by Xuhao** [xuexiangjys/flutter_xupdate#70]
**问题描述（必填）**

调试模式能正常识别新版本，并正常下载、安装，模拟器和真机都正常
但是打了 release 包之后，真机安装后，一直提示**已是最新版本!**,  无论如何调整`VersionCode`, 都一样提示已是最新版

**使用的flutter_xupdate版本（必填）**
flutter_xupdate：1.0.2
flutter: 1.22.6
dart: 2.10.5

**如何重现（必填）**

重现的步骤:
1. 通过 `flutter build apk --no-shrink` 打正式包，然后真机安装
2. 修改 update.json， 调高 `VersionCode`,  然后触发 `FlutterXUpdate.checkUpdate` 检查更新

**期望的效果**

打了正式包，安装后也能正常识别新版本

**截图**

无

**设备信息**

 - 设备名: Huawei P30 lite
 - Android版本: 10
 - 设备型号: MAR-LX2
 - 系统版本: EMUI 10

**附加信息**

由于历史项目使用 flutter 1.22.6， 所以只能使用1.0.2版的 flutter_xupdate

**Comment by xuexiangjys** [comment]
按照[常见问题](https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%B0%83%E8%AF%95%E7%9A%84%E4%BD%BF%E7%94%A8%E6%98%AF%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0%E7%9A%84%E4%BD%86%E6%98%AF%E4%BD%BF%E7%94%A8flutter-build-apk---release%E6%89%93%E5%87%BA%E6%9D%A5%E7%9A%84%E5%8C%85%E5%8D%B4%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%9B%B4%E6%96%B0)进行处理,
实在不行把混淆关闭了.
