### ISSUE TITLE
更新依据会判断versionName吗，versionCode我应该如何处理

### ISSUE THREAD

**Issue by cn1001wang** [xuexiangjys/flutter_xupdate#72]
**问题描述（必填）**
VersionCode如何手动设置，比如我一开始是链接下载的，他其实和线上是相同版本，但是点击查询更新，因为本地的VersionCode没有，他就会认为是需要更新

**使用的flutter_xupdate版本（必填）**
2.0.2

**如何重现（必填）**
重现的步骤:
1. 链接下载1.1.0版本APP
2. 线上update.json文件 为{"VersionName": "1.1.0","VersionCode": 4,"UpdateStatus": 1,}
3. 点击查询更新
4. 展示需要更新

**期望的效果**
1.需要能够本地设置code
2.或者是我的使用方式不正确

**截图**
![image](https://user-images.githubusercontent.com/34416681/149053409-e9d31382-c898-4b51-8a0b-48f22d0f57f9.png)

**Comment by cn1001wang** [comment]
我好像懂了，我看到[源码](https://github.com/xuexiangjys/XUpdate/blob/21147a9baadefb9240e445482c718ee334fae1ea/xupdate-lib/src/main/java/com/xuexiang/xupdate/utils/UpdateUtils.java#L397)中应该是去找build.gradle的versioncode，让我先试试。因为我是前端出身，Android并不熟悉。

**Comment by cn1001wang** [comment]
源码中是不是不判断versionName，所以versionCode应该要一直向上累加吗？

**Comment by xuexiangjys** [comment]
Android原生能否升级更新都是根据这个versionCode这个字段来的,只要有修改都应该更新versionCode
