### ISSUE TITLE
打正式包失败

### ISSUE THREAD

**Issue by SilentlyYc** [xuexiangjys/flutter_xupdate#73]
**问题描述（必填）**
正式包会提示缺失图片文件

**使用的flutter_xupdate版本（必填）**
2.0.2

**如何重现（必填）**
集成后无论是--release --verbose还是build apk，都会报缺失文件，但是开发不会

**截图**
错误信息
![image](https://user-images.githubusercontent.com/16175937/149747715-63744ea0-9479-4244-8d80-59081448a0ef.png)

不知道是不是解决办法的解决办法是
![image](https://user-images.githubusercontent.com/16175937/149748072-3e60b9b8-f007-4fd7-bd14-272c31660ce3.png)
我把这个注释了打包就没有问题了。更新貌似正常

flutter 2.8.1

**Comment by SilentlyYc** [comment]
但是我看github上这个文件没有包含我注释的代码，不知道是什么情况

**Comment by SilentlyYc** [comment]
莫名其妙的BUG，我清除Flutter SDK中的缓存，然后Flutter clean，作废缓存重启，重新拉的没有这段代码了，不清楚是什么原因。但是问题应该是解决了。问题关闭

**Comment by xuexiangjys** [comment]
> 莫名其妙的BUG，我清除Flutter SDK中的缓存，然后Flutter clean，作废缓存重启，重新拉的没有这段代码了，不清楚是什么原因。但是问题应该是解决了。问题关闭

遇事不决，首先clean，这是好习惯

**Comment by SilentlyYc** [comment]
> > 莫名其妙的BUG，我清除Flutter SDK中的缓存，然后Flutter clean，作废缓存重启，重新拉的没有这段代码了，不清楚是什么原因。但是问题应该是解决了。问题关闭
> 
> 遇事不决，首先clean，这是好习惯

主要这次我是删了SDK中的缓存，光clean是没作用的，顺便问一句，这个在原生项目配置style主题样式能不加么，想无感引入。不是专业安卓，不知道是否能实现，请教一下

**Comment by xuexiangjys** [comment]
其实是可以,换一下布局就行了
