### ISSUE TITLE
Device and Network Abuse Policy

### ISSUE THREAD

**Issue by chengboonrong** [xuexiangjys/flutter_xupdate#74]
![WhatsApp Image 2022-01-05 at 2 57 16 PM](https://user-images.githubusercontent.com/21172662/150711598-f37fd861-257a-4d73-ab2f-90967c4750a3.jpeg)

I am facing this issue when trying to submit my app to Google Play. 
Can you advise how to solve this?

**Comment by xuexiangjys** [comment]
change the download address to the address of google play

**Comment by qs991011** [comment]
文件下载不支持http吗
