### ISSUE TITLE
在调用FlutterXUpdate.updateByInfo控制台打印W/libEGL  (19625): EGLNativeWindowType 0x76e978a010 disconnect failed  界面无反应

### ISSUE THREAD

**Issue by qq627314025** [xuexiangjys/flutter_xupdate#77]
这是我调用初始化的方法
FlutterXUpdate.init(

              ///是否输出日志
              debug: true,

              ///是否使用post请求
              isPost: false,

              ///post请求是否是上传json
              isPostJson: false,

              ///请求响应超时时间
              timeout: 25000,

              ///是否开启自动模式
              isWifiOnly: true,

              ///是否开启自动模式
              isAutoMode: false,

              ///需要设置的公共参数
              supportSilentInstall: false,

              ///在下载过程中，如果点击了取消的话，是否弹出切换下载方式的重试提示弹窗
              enableRetry: false)
          .then((value) {
        print("初始化成功: $value");
      }).catchError((error) {
        print(error);
      });

控制台打印   
[GETX] Instance "HomeLogic" has been created
D[XUpdate](19625): 设置全局是否使用的是Get请求:true
D[XUpdate](19625): 设置全局是否只在wifi下进行版本更新检查:true
D[XUpdate](19625): 设置全局是否是自动版本更新模式:false
D[XUpdate](19625): 设置全局参数, key:versionCode, value:1
D[XUpdate](19625): 设置全局参数, key:appKey, value:com.hykc.cityfreight
D[XUpdate](19625): 设置请求超时响应时间:25000ms, 是否使用json:false
D[XUpdate](19625): 设置全局更新网络请求服务:com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService
I[/flutter]() (19625): 初始化成功: {isPostJson: false, isGet: true, debug: true, retryContent: , isWifiOnly: true, isAutoMode: false, supportSilentInstall: false, retryUrl: , params: null, enableRetry: false, timeout: 25000}

下面是我调用更新的方法
FlutterXUpdate.updateByInfo(
        updateEntity: UpdateEntity(
            hasUpdate: true,
            updateContent: _upgradeInfo.newFeature,
            downloadUrl: _upgradeInfo.apkUrl,
            versionCode: _upgradeInfo.versionCode,
            versionName: _upgradeInfo.versionName,
            isForce: _upgradeInfo.upgradeType == 2,
            apkSize: _upgradeInfo.fileSize),
        supportBackgroundUpdate: true,
        topImageRes: 'bg_update_top',
        themeColor: '#FFFF9800',
        buttonTextColor: '#FFFFFFFF',
      );
apkUrl      
apkUrl = [https://outexp-beta.cdn.qq.com/outbeta/2022/02/18/comhykccityfreight_1.0.1_327d179c-089c-52f8-9d09-583e18a51b04.apk]()
安卓也进行配置
<resources>
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
 项目运行的配置环境
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-US)
    • Flutter version 2.10.1 at /Users/hanqiang/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (9 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
    • Android SDK at /Users/hanqiang/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
[✓] VS Code (version 1.64.2)
    • VS Code at /Users/hanqiang/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • HUAWEI NXT AL10 (mobile) • CJL7N15C15007365 • android-arm64  • Android
      8.0.0 (API 26)
    • macOS (desktop)          • macos            • darwin-x64     • macOS 12.1
      21C52 darwin-x64
    • Chrome (web)             • chrome           • web-javascript • Google
      Chrome 95.0.4638.69
运行的手机    HUAWEI NXT AL10 (mobile) • CJL7N15C15007365 • android-arm64  • Android
      8.0.0 (API 26)

**Comment by xuexiangjys** [comment]
没有看到任何有用的信息

**Comment by qq627314025** [comment]
问题已经解决  不是插件的问题   是我topImageRes: 'bg_update_top',   这个图片设置的问题   我取消了然后使用默认的图片就搞定了

**Comment by w4mxl** [comment]
@qq627314025 https://github.com/flutter/flutter/issues/98245 我这边遇到你这个 issue 中的问题了，能请教一下代码层面你后来是如何解决的吗。你提到升级了手机浏览器内核，这个是通过更新手机系统还是其它什么操作呢

（ps. 那边 issue 被 locked 了，这能在这儿问下了）
