### ISSUE TITLE
在强制更新模式下，弹窗在更新完成后没有关闭

### ISSUE THREAD

**Issue by msidolphin** [xuexiangjys/flutter_xupdate#8]
并且无法使用返回键退出应用

**Comment by xuexiangjys** [comment]
这里的应用更新都是全量更新, 应用更新完成之后是会被杀死的,明白不?这里不需要关闭.
你如果是跑的demo看到这现象,那是因为我demo里面更新的并不是同一个app,我只是演示这个更新过程而已.
