### ISSUE TITLE
Debug开发没有问题，打包出来之后提示”已是最新版本“，按照您解决方案里三种都试了，不起作用。

### ISSUE THREAD

**Issue by xiangffgh** [xuexiangjys/flutter_xupdate#80]
以下是日志记录：实际App的VersionCode是:1.0.0，需升级到 201
04-14 09:56:46.185 D/SignalClusterView( 1610): updateMobileTypeImage  0
04-14 09:56:46.265 D/[XUpdate]( 7689): XUpdate.update()启动:XUpdate{mUpdateUrl='http://vubwzb.natappfree.cc/ndd/appinfo/query/latest', mParams={appKey=com.xiangff.cunlihao, currentVersion=1.0.0, versionCode=2}, mApkCacheDir='/storage/emulated/0/Android/data/com.xiangff.cunlihao/cache/xupdate', mIsWifiOnly=false, mIsGet=true, mIsAutoMode=false}
04-14 09:56:46.266 D/[XUpdate]( 7689): 开始检查版本信息...
04-14 09:56:46.277 I/hwcomposer(  587): [DPY] receive refesh frquest from driver: type[4]  
04-14 09:56:46.277 I/hwcomposer(  587): [HWC] fire a callback of refresh to SF  
04-14 09:56:46.287 I/BufferQueueProducer(  654): [FramebufferSurface](this:0x748f3e3800,id:0,api:1,p:587,c:654) queueBuffer: fps=1.09 dur=2758.54 max=1997.89 min=197.53
04-14 09:56:46.290 E/ResolverController(  571): No valid NAT64 prefix (241, <unspecified>/0)
04-14 09:56:46.291 I/System.out( 7689): [socket]:check permission begin!
04-14 09:56:46.291 W/System  ( 7689): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
04-14 09:56:46.292 I/System.out( 7689): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
****04-14 09:56:46.495 I/[XUpdate]( 7689): 服务端返回的最新版本信息:{"Code":0,"Msg":null,"UpdateStatus":2,"VersionCode":201,"VersionName":"2.0.1","ModifyContent":"1、优化界面。\\r\\n2、修改未知Bug。\\r\\n","DownloadUrl":"http://ztfile.oss-cn-beijing.aliyuncs.com/jxpt/nongch/app/app-release-1.0.1-20220414.apk","ApkSize":22,"ApkMd5":null}
04-14 09:56:46.497 I/[XUpdate]( 7689): 未发现新版本!
04-14 09:56:46.498 I/flutter ( 7689): {code: 2004, detailMsg: Code:2004, msg:已是最新版本！, message: 已是最新版本！}****
04-14 09:56:46.537 D/MemoryCeilingMonitor( 5466): [handleMemoryCalculate]
04-14 09:56:46.537 D/MemoryCeilingMonitor( 5466): [calculate] tot: 4248853, max: 268435456, free: 469701, heap: 3779152, per: 0.01407843828201294
04-14 09:56:47.037 I/ADB_SERVICES( 7308): service_to_fd shell:dumpsys iphonesubinfo
04-14 09:56:47.050 I/ADB_SERVICES( 7308): post waitpid (pid=7857) status=0000
04-14 09:56:47.

**Comment by xuexiangjys** [comment]
你要是实在找不到解决的方法,就直接取消混淆.
把minifyEnabled设置成false
`minifyEnabled false`
