### ISSUE TITLE
希望提供当用户忽略后仍可以弹出更新提示框的方法

### ISSUE THREAD

**Issue by Jovines** [xuexiangjys/flutter_xupdate#82]
场景：用户进入App使用默认检查更新方法更新，当用户忽略更新后。用户可能会进入app设置页面中点击检查更新，主动更新App

**Comment by xuexiangjys** [comment]
你可以把sdk更新到2.1.2就可以支持了
https://github.com/xuexiangjys/XUpdate/releases/tag/2.1.2
