### ISSUE TITLE
请问md5加密需要我额外操作么？目前打包后使用demo获取不到md5值

### ISSUE THREAD

**Issue by chenshaxuanjing** [xuexiangjys/flutter_xupdate#83]
![1B4083F25C96FB355AE6C36600704BC4](https://user-images.githubusercontent.com/32640500/172051995-df1e2c74-60dc-4dc7-ba3c-66134216fdfd.jpg)
用xupdate那边的demo1.0 apk获取，计算MD5值，没有结果

**Comment by xuexiangjys** [comment]
怕不是你的apk有问题吧,把你的apk上传给我看一下

**Comment by chenshaxuanjing** [comment]
> 怕不是你的apk有问题吧,把你的apk上传给我看一下
@xuexiangjys 
[20220607.zip](https://github.com/xuexiangjys/flutter_xupdate/files/8852863/20220607.zip)

**Comment by xuexiangjys** [comment]
你apk的位置在外部存储,已经做兼容了
https://github.com/xuexiangjys/XUpdate/commit/c7584f2cbeb9af42b4f782c878544e6454772971
