### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Kenmmm** [xuexiangjys/flutter_xupdate#84]
你好，我这边看到log，更新文件下载完成,
开始安装apk文件,
就卡在这一步了，去文件管理也能找到这个apk。一直未安装，也不提示失败。。

**Comment by xuexiangjys** [comment]
你的签名有冲突,安装不上很正常

**Comment by Kenmmm** [comment]
嗯，不是签名的问题，加上md5就好了。我看到这个不是必传的吧。。。
