### ISSUE TITLE
请问如果使用自定义json，是否更新就是通过hasUpdate判断吗？

### ISSUE THREAD

**Issue by fyang0728** [xuexiangjys/flutter_xupdate#87]
**问题描述（必填）**

我用了自定义json，不管versionCode 怎么变 hasUpdate是true的话 都会提示更新。

还是说用了自定义json，hasUpdate 需要自己判断触发一下呢？

**使用的flutter_xupdate版本（必填）**

2.0.3

**Comment by xuexiangjys** [comment]
如果使用了自定义json的话，是否需要更新是由你自己来做判断的，只要是 hasUpdate是true的话，就会提示更新。
