### ISSUE TITLE
升级时下载了安装包后没有弹出xupdate的安装窗口

### ISSUE THREAD

**Issue by hmlss** [xuexiangjys/flutter_xupdate#88]
**问题描述（必填）**
下载完apk文件后没有弹出安装窗口.
尝试了发布多个版本的APK, 有一个(1.0.8)可以成功安装,但其他的(如1.0.7和1.0.9)全卡在了升级之后的步骤.
apkMD5已设置且用官方demoapk确认计算无误
APK签名均为release签名,且经过人工的keytool命令查询确认
versionCode分别为107(失败),108(成功)和109(失败)
所有版本均可以人工下载安装
在另外的鸿蒙和Android9的手机下测试都是同样的结果
所有APK打包方式均相同,唯一区别是 pubspec.yaml 下 version 字段不同, 分别为 1.0.7+107, 1.0.8+108 和 1.0.9+109

**使用的flutter_xupdate版本（必填）**
1.0.8

**如何重现（必填）**
重现的步骤:
1. 进入APP
2. 弹出升级窗口,点击升级
3. 下载完成后无后续响应

**期望的效果**
下载完成后弹出安装窗口

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 华为 HONOR Play4T Pro
 - Android版本: HarmonyOS 2.0.0
 - 设备型号 AQM-AL10
 - 系统版本 2.0.0.269

**附加信息**

**Comment by hmlss** [comment]
补充失败日志
I/[XUpdate](32396): 开始下载更新文件:UpdateEntity{mHasUpdate=true, mIsForce=false, mIsIgnorable=false, mVersionCode=109, mVersionName='1.0.9', mUpdateContent='更新了
一些bug', mDownloadEntity=DownloadEntity{mDownloadUrl='http://192.168.1.102:5003/Common/File?version=1.0.9', mCacheDir='/storage/emulated/0/Android/data/com.example.
phot_flutter_app/cache/xupdate', mMd5='C2BF767B8692E634CA7D245B14AB', mSize=33481, mIsShowNotification=false}, mIsSilent=false, mIsAutoInstall=true, mIUpdateHttpServ
ice=com.xuexiang.flutter_xupdate.OKHttpUpdateHttpService@21def0f}
D/[XUpdate](32396): 开始下载更新文件, 下载地址:http://192.168.1.102:5003/Common/File?version=1.0.9, 保存路径:/storage/emulated/0/Android/data/com.example.phot_flutte
r_app/cache/xupdate/1.0.9, 文件名:temp_1664446390033.apk
D/[XUpdate](32396): 正在回收资源...
D/[XUpdate](32396): 更新文件下载完成, 文件路径:/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate/1.0.9/temp_1664446390033.apk
D/[XUpdate](32396): 开始安装apk文件, 文件路径:/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate/1.0.9/temp_1664446390033.apk, 下载信息:Down
loadEntity{mDownloadUrl='http://192.168.1.102:5003/Common/File?version=1.0.9', mCacheDir='/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate
', mMd5='C2BF767B8692E634CA7D245B14AB', mSize=33481, mIsShowNotification=false}

成功日志
D/[XUpdate](31824): 开始下载更新文件, 下载地址:http://192.168.1.102:5003/Common/File?version=1.0.8, 保存路径:/storage/emulated/0/Android/data/com.example.phot_flutte
r_app/cache/xupdate/1.0.8, 文件名:temp_1664446156048.apk
D/[XUpdate](31824): 正在回收资源...
D/[XUpdate](31824): 更新文件下载完成, 文件路径:/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate/1.0.8/temp_1664446156048.apk
D/[XUpdate](31824): 开始安装apk文件, 文件路径:/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate/1.0.8/temp_1664446156048.apk, 下载信息:Down
loadEntity{mDownloadUrl='http://192.168.1.102:5003/Common/File?version=1.0.8', mCacheDir='/storage/emulated/0/Android/data/com.example.phot_flutter_app/cache/xupdate
', mMd5='', mSize=33481, mIsShowNotification=false}
I/TPush   (31824): [XGPushProvider] getType uri:content://com.example.phot_flutter_app.XGVIP_PUSH_AUTH/hbcyheck,match:82
D/TPush   (31824): [NotificationsUtils] onCheckNotification registerStatus: 1
I/TPush   (31824): [NotificationsUtils] OS >= 26, return true
D/TPush   (31824): [NotificationsUtils] lastNtfStr:c81e728d9d4c2f636f067f89cc14862c
D/TPush   (31824): [NotificationsUtils] currentNtfStr:c81e728d9d4c2f636f067f89cc14862c
D/TPush   (31824): [NotificationsUtils] notification not changed, or unRegistered

**Comment by xuexiangjys** [comment]
看了你的日志, 成功的日志没有设置mMd5,所以没有进行md5文件校验,但是失败的是有设置mMd5,所以我推测你是MD5校验没有成功导致.

**Comment by hmlss** [comment]
谢谢,我明天让我的同事确认一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuexiangjys/flutter_xupdate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuexiangjys/flutter_xupdate] 升级时下载了安装包后没有弹出xupdate的安装窗口 (Issue #88)





 
看了你的日志, 成功的日志没有设置mMd5,所以没有进行md5文件校验,但是失败的是有设置mMd5,所以我推测你是MD5校验没有成功导致.
