### ISSUE TITLE
更新下载完成后，安装失败

### ISSUE THREAD

**Issue by Maclaon** [xuexiangjys/flutter_xupdate#9]
下载完成后，开始安装，但是安装失败！

**Comment by xuexiangjys** [comment]
有问题请先自己自行解决:https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#6%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E5%BA%94%E7%94%A8%E4%B8%8B%E8%BD%BD%E4%BA%86%E4%BD%86%E6%98%AF%E7%82%B9%E5%87%BB%E5%AE%89%E8%A3%85%E6%8C%89%E9%92%AE%E5%90%8E%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0%E5%A4%B1%E8%B4%A5%E5%91%A2

还是解决不了,麻烦你把失败原因写清楚,ok?

**Comment by Maclaon** [comment]
说的对，小弟造次了~打开`adb logcat`应该是签名问题
