### ISSUE TITLE
后台升级可以多次点击升级，多个包在后台下载

### ISSUE THREAD

**Issue by summeryi** [xuexiangjys/flutter_xupdate#90]
1.同一个版本，点击升级后，再次点击后台下载，弹窗消失
2.然后再次触发升级，重复步骤1，导航栏显示多个进度在走

**Comment by summeryi** [comment]
该问题在version 2.0.3 中出现

**Comment by xuexiangjys** [comment]
请提供你的写法和日志

**Comment by xuexiangjys** [comment]
另外, 对于判断是否在升级中, 框架是在开始检查版本的地方进行校验的,如果你使用的是`Update By UpdateEntity Directly`方法, 是不会进行重新性校验的,这需要你自己去做

**Comment by summeryi** [comment]
对的，我调用升级方式是：FlutterXUpdate.updateByInfo
最后我处理的方式是，延迟检测下载路径下，整个包大小有没有变化，来判断是否升级中

建议下个版本，可以增加是否下载中的方法，谢谢！

**Comment by lingdianjiyi** [comment]
我现在也遇到了这个问题，请问大佬儿是如何做的，希望可以贴出部分代码
