### ISSUE TITLE
设置弹框的顶部自定义图片，在安卓手机上可以读取，但是在安卓的手持设备上无法读取。弹框界面显示异常

### ISSUE THREAD

**Issue by ichenwanbing** [xuexiangjys/flutter_xupdate#93]
设置弹框的顶部自定义图片，在安卓手机上可以读取，但是在安卓的手持设备上无法读取。弹框界面显示异常

**截图**
![image](https://user-images.githubusercontent.com/18181880/204422630-7e12dd58-623b-473e-a077-a78c026543a2.png)

![image](https://user-images.githubusercontent.com/18181880/204422570-15937003-d5f6-46a0-9cae-9e6f733f7d5c.png)

![c4a47438f47bf8351e309f86937fbb1](https://user-images.githubusercontent.com/18181880/204423051-83f9a6f7-36f9-4ba3-ae8f-879ec08de906.jpg)

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/flutter_xupdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%B9%E6%A1%86%E6%A0%B7%E5%BC%8F%E7%9A%84%E9%A1%B6%E9%83%A8%E5%9B%BE%E7%89%87debug%E4%B8%8B%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA%E4%BD%86%E6%98%AF%E5%9C%A8release%E4%B8%8B%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA
