### ISSUE TITLE
希望提供当用户忽略后仍可以弹出更新提示框的方法 flutter插件

### ISSUE THREAD

**Issue by axiaofang666** [xuexiangjys/flutter_xupdate#97]
场景：用户进入App使用默认检查更新方法更新，当用户忽略更新后。用户可能会进入app设置页面中点击检查更新，主动更新App
flutter插件

**Comment by xuexiangjys** [comment]
可以使用自定义解析json或者直接传入UpdateEntity进行更新提示

只要设置UpdateEntity中的`isIgnorable`字段为false即可
