### ISSUE TITLE
进度条没有动态增长的效果，只是显示0%

### ISSUE THREAD

**Issue by 18804032217** [xuexiangjys/flutter_xupdate#98]
版本升级弹窗正常显示，点击升级之后也会下载，apk大概是80M，但是进度条没有动态增长的效果，只是显示0%，请问是为什么啊？

**Comment by xuexiangjys** [comment]
参考这个：
https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%82%B9%E5%87%BB%E4%B8%8B%E8%BD%BD%E5%90%8E%E6%96%87%E4%BB%B6%E6%98%AF%E8%83%BD%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E7%9A%84%E4%BD%86%E6%98%AF%E8%BF%9B%E5%BA%A6%E6%9D%A1%E4%B8%8D%E6%9B%B4%E6%96%B0%E6%88%96%E8%80%85%E6%89%93%E5%8D%B0%E5%87%BA%E8%BF%9B%E5%BA%A6%E6%9D%A1%E7%9A%84%E5%80%BC%E6%98%AF-1
