### ISSUE TITLE
选择后台更新后，页面初始化还会调起升级窗口

### ISSUE THREAD

**Issue by lingdianjiyi** [xuexiangjys/flutter_xupdate#99]
flutter_xupdate版本：2.0.3
另外在[#90 ]中看您提到对于判断是否在升级中, 框架是在开始检查版本的地方进行校验的，然而我仔细阅读代码后并没有看到有判断是否在升级中的代码。
希望大佬儿看到能回复一下，谢谢！

**Comment by lingdianjiyi** [comment]
或者我应如何获取当前后台的下载进度，自己进行判断

**Comment by xuexiangjys** [comment]
2.0.4已解决这个问题
